### ISSUE TITLE
problem with function cvFindChessboardCorners3()

### ISSUE THREAD

**Issue by riyueshi** [adasworks/ocamcalib-plus#2]
Hi,
  while I am using the function "cvFindChessboardCorners3()". there is no output in the params "CvPoint2D32f* out_corners" and "int* out_corner_count". can you tell me where I can find the complete code to find the chessboard corners, thank you.

**Comment by tamaskenez** [comment]
The source of that function is [here](https://github.com/adasworks/ocamcalib-plus/blob/565638f881dbf7c32c0f4abc14c9edd1a788acd3/autoCornerFinder/cvcalibinit3.cpp#L122). It has not been modified by us.

Also, in our application we don't use this function. Instead, we're using OpenCV's [findChessboardCorners()](http://docs.opencv.org/3.1.0/d9/d0c/group__calib3d.html#ga93efa9b0aa890de240ca32b11253dd4a)

**Comment by riyueshi** [comment]
thanks, I have got the result in the output text files in folder 'cToMatlab'
