### ISSUE TITLE
problem about the rotation matrix

### ISSUE THREAD

**Issue by riyueshi** [adasworks/ocamcalib-plus#4]
Hi, I got some problem about the rotation matrix obtained by the ocamcalib-plus. I used the same images as input data to calibrate the camera both openCV and ocamcalib-plus. the rotation matrix they got is quite different and after I convert the rotation matrix to euler angle I find that two of the angle value have opposite sign (eg. [2.1,0.8,1.6] in openCV and [2.1,-0.8,-1.6] in ocamcalib-plus). I am curious about how this occur. Is that just a difference of the sign define?  and what kind of coordinate the ocamlib-plus use, right hand or left hand? if it is a left hand coordinate how could I convert all the element to a right hand coordinate?
Miller

**Comment by tamaskenez** [comment]
Hi,
ocamcalib uses this (rather strange) camera-space coordinate system:
+x downwards
+y right
+z backwards
So it's still right handed.

**Comment by riyueshi** [comment]
Got it, thanks a lot
